if (NOT GLEW_FOUND)
  message("Installing GLEW...")
	set(GLEW_FOUND ON CACHE BOOL "")
	set(GLEWPath "${THIRD_PARTIES}/GLEW")
	
	set(GLEW_INCLUDE_DIR "${GLEWPath}/include" CACHE PATH "")
	set(GLEW_INCLUDE_DIRS "${GLEWPath}/include" CACHE PATH "")
	if(CMAKE_SIZEOF_VOID_P EQUAL 8)
		set(GLEW_LIBRARY_DIRS "${GLEWPath}/lib/x64" CACHE PATH "")
    set(GLEW_LIBRARIES glew32.lib glew32s.lib CACHE PATH "")
		set(GLEW_BINARY "${GLEWPath}/bin/x64/glew32.dll" CACHE PATH "")
	else()
		set(GLEW_LIBRARY_DIRS "${GLEWPath}/lib/x32" CACHE PATH "")
    set(GLEW_LIBRARIES glew32.lib glew32s.lib CACHE PATH "")
		set(GLEW_BINARY "${GLEWPath}/bin/x32/glew32.dll" CACHE PATH "")
	endif()
endif()

include_directories(${GLEW_INCLUDE_DIRS})
link_directories(${GLEW_LIBRARY_DIRS})